#include "game_manager.h"
#include "game_session_internal.h"
#include "save_internal.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void Require(bool ok,const char *message){if(!ok){fprintf(stderr,"save_multi_map smoke failed: %s\n",message);exit(1);}}
static void Reset(Game *game){memset(game,0,sizeof(*game));Game_ResetGameplayWorld(game);game->flow.state=GAME_STATE_PLAYING;}
static void ExitShip(Game *game){const MapPortal *p=Map_GetPortalById(&game->runtime.map,"SHIP_AIRLOCK_EXIT");Require(p&&Game_BeginPortalTransition(game,p),"exit portal should start");Require(Game_ResolveMapTransition(game),"exit portal should resolve");game->flow.screenTransitionActive=false;game->flow.screenTransitionAction=SCREEN_TRANSITION_NONE;Game_FinishMapTransition(game);}
int main(void){
 Game game,loaded,legacyLoaded; SaveSnapshot *snap=(SaveSnapshot*)calloc(1,sizeof(SaveSnapshot)),*decoded=(SaveSnapshot*)calloc(1,sizeof(SaveSnapshot)); uint8_t *buffer=(uint8_t*)malloc(SAVE_INTERNAL_MAX_SAVE_FILE_SIZE); size_t size=0; int surfaceNode=-1,surfaceMonster=-1,surfaceLog=-1;
 Require(snap&&decoded&&buffer,"test allocations should succeed");Reset(&game);game.runtime.tasks.stage=6;game.runtime.player.resources[RESOURCE_ORE]=17;ExitShip(&game);Require(strcmp(game.runtime.map.mapId,"planet_surface_01")==0,"player should be on formal surface");
 game.runtime.player.gridX=90;game.runtime.player.gridY=60;Player_UpdateWorldPosition(&game.runtime.player);Map_SetUnlockOpen(&game.runtime.map,"RUINS_GATE",true);Map_SetFieldCamp(&game.runtime.map,90,60);
 for(int i=0;i<game.runtime.tasks.nodeCount;i++)if(strcmp(game.runtime.tasks.nodes[i].mapId,"planet_surface_01")==0){surfaceNode=i;break;}
 for(int i=0;i<game.runtime.tasks.monsterCount;i++)if(strcmp(game.runtime.tasks.monsters[i].mapId,"planet_surface_01")==0){surfaceMonster=i;break;}
 for(int i=0;i<game.runtime.tasks.logCount;i++)if(strcmp(game.runtime.tasks.logs[i].mapId,"planet_surface_01")==0){surfaceLog=i;break;}
 Require(surfaceNode>=0&&surfaceMonster>=0&&surfaceLog>=0,"surface entities should be registered");game.runtime.tasks.nodes[surfaceNode].active=false;game.runtime.tasks.nodes[surfaceNode].respawnsRemaining=1;game.runtime.tasks.monsters[surfaceMonster].health=7.0f;game.runtime.tasks.monsters[surfaceMonster].phaseTriggered=true;game.runtime.tasks.logs[surfaceLog].collected=true;
 Game_BuildSaveSnapshot(&game,snap);Require(strcmp(snap->currentMapId,"planet_surface_01")==0&&snap->mapStateCount>=2,"V16 snapshot should contain current map and multiple map states");Require(SaveInternal_EncodeSnapshotBuffer(snap,buffer,SAVE_INTERNAL_MAX_SAVE_FILE_SIZE,&size),"V16 encode should succeed");Require(SaveInternal_DecodeSnapshotBuffer(decoded,buffer,size),"V16 decode should succeed");Require(decoded->sourceVersion==16&&strcmp(decoded->currentMapId,"planet_surface_01")==0,"V16 identity should round-trip");
 Reset(&loaded);Game_LoadSnapshotIntoSession(&loaded,decoded);Require(strcmp(loaded.runtime.map.mapId,"planet_surface_01")==0,"surface save should load on same map");Require(loaded.runtime.player.gridX==90&&loaded.runtime.player.gridY==60,"surface coordinates should round-trip");Require(loaded.runtime.player.resources[RESOURCE_ORE]==17&&loaded.runtime.tasks.stage==6,"global player and task state should survive load");Require(Map_IsUnlockOpen(&loaded.runtime.map,"RUINS_GATE")&&loaded.runtime.map.campPlaced,"surface unlock and camp should restore");Require(!loaded.runtime.tasks.nodes[surfaceNode].active&&loaded.runtime.tasks.nodes[surfaceNode].respawnsRemaining==1,"surface resource state should restore");Require(loaded.runtime.tasks.monsters[surfaceMonster].health==7.0f&&loaded.runtime.tasks.monsters[surfaceMonster].phaseTriggered,"surface monster state should restore");Require(loaded.runtime.tasks.logs[surfaceLog].collected,"surface log state should restore");
 snap->gridX=63;snap->gridY=52;snap->resources[RESOURCE_METAL_SCRAP]=9;snap->stage=5;Require(SaveInternal_EncodeLegacyV15Buffer(snap,buffer,SAVE_INTERNAL_MAX_SAVE_FILE_SIZE,&size),"V15 fixture encode should succeed");memset(decoded,0,sizeof(*decoded));Require(SaveInternal_DecodeSnapshotBuffer(decoded,buffer,size)&&decoded->sourceVersion==15,"V15 decoder should remain available");Reset(&legacyLoaded);Game_LoadSnapshotIntoSession(&legacyLoaded,decoded);Require(strcmp(legacyLoaded.runtime.map.mapId,"ship_interior")==0,"V15 Base coordinates should migrate to ship interior");Require(legacyLoaded.runtime.player.resources[RESOURCE_METAL_SCRAP]==9&&legacyLoaded.runtime.tasks.stage==5,"V15 migration should preserve inventory and tasks");
 snap->gridX=125;snap->gridY=103;Require(SaveInternal_EncodeLegacyV15Buffer(snap,buffer,SAVE_INTERNAL_MAX_SAVE_FILE_SIZE,&size),"outdoor V15 fixture encode should succeed");memset(decoded,0,sizeof(*decoded));Require(SaveInternal_DecodeSnapshotBuffer(decoded,buffer,size),"outdoor V15 decode should succeed");Game_LoadSnapshotIntoSession(&legacyLoaded,decoded);Require(strcmp(legacyLoaded.runtime.map.mapId,"planet_surface_01")==0,"non-Base V15 coordinates should migrate to formal surface");Require(!(legacyLoaded.runtime.player.gridX==125&&legacyLoaded.runtime.player.gridY==103)&&Map_IsWalkable(&legacyLoaded.runtime.map,legacyLoaded.runtime.player.gridX,legacyLoaded.runtime.player.gridY),"invalid migrated coordinates should repair to a safe surface tile");
 Map_Destroy(&game.runtime.map);MapSceneManager_Destroy(&game.services.mapScene);Map_Destroy(&loaded.runtime.map);MapSceneManager_Destroy(&loaded.services.mapScene);Map_Destroy(&legacyLoaded.runtime.map);MapSceneManager_Destroy(&legacyLoaded.services.mapScene);free(buffer);free(decoded);free(snap);puts("save_multi_map smoke ok");return 0;
}
