#ifndef CONFIG_H
#define CONFIG_H

/* Shared gameplay, map, camera, and tuning constants used across runtime modules. */

#define WINDOW_TITLE "SpaceCraft Living"
#define WINDOW_WIDTH 1440
#define WINDOW_HEIGHT 900
#define WINDOW_MIN_WIDTH 1180
#define WINDOW_MIN_HEIGHT 760
#define WINDOW_MONITOR_FILL 0.86f
#define TARGET_FPS 60

#define TILE_SIZE 96
#define CAMERA_ZOOM 0.88f
#define MAP_WIDTH 126
#define MAP_HEIGHT 104

#define INITIAL_HEALTH 100.0f
#define BASE_MAX_HEALTH 100.0f
#define INITIAL_STAMINA 100.0f
#define BASE_MAX_STAMINA 100.0f
#define INITIAL_PRESSURE 0.0f
#define MAX_PRESSURE 100.0f
#define INITIAL_OXYGEN 100.0f
#define MAX_OXYGEN 100.0f
#define MAX_POISON 100.0f

#define NORMAL_MOVE_COOLDOWN 0.18f
#define LOW_STAMINA_MOVE_COOLDOWN 0.28f
#define CROUCH_MOVE_COOLDOWN 0.28f
#define BLOCKED_MOVE_COOLDOWN 0.09f
#define INPUT_BUFFER_TIME 0.12f
#define HOLD_REPEAT_INITIAL_DELAY 0.26f
#define HOLD_REPEAT_INTERVAL 0.10f
#define STAMINA_LOW_THRESHOLD 32.0f
#define STAMINA_MOVE_COST 0.5f
#define STAMINA_GATHER_COST 4.0f
#define STAMINA_SPECIAL_GATHER_COST 5.5f
#define STAMINA_ATTACK_COST 2.5f

#define SAFE_RECOVERY_INTERVAL 1.25f
#define SAFE_RECOVERY_AMOUNT 4.0f
#define PRESSURE_DAMAGE_INTERVAL 1.0f
#define HAZARD_TICK_INTERVAL 0.50f

#define DAY_DURATION_SECONDS 600.0f
#define DUSK_DURATION_SECONDS 120.0f
#define NIGHT_DURATION_SECONDS 480.0f
#define FULL_CYCLE_SECONDS (DAY_DURATION_SECONDS + DUSK_DURATION_SECONDS + NIGHT_DURATION_SECONDS)
#define DAY_COUNT_DURATION_SECONDS 300.0f
#define SLEEP_TIME_ADVANCE_SECONDS 60.0f

#define PLAYER_START_X 63
#define PLAYER_START_Y 52

#define EXTERIOR_SCALE_NUM 4
#define EXTERIOR_SCALE_DEN 5
#define EXTERIOR_SCALE_ROUND (EXTERIOR_SCALE_DEN / 2)
#define EXTERIOR_SCALE_DELTA(delta) \
    (((delta) >= 0) \
        ? (((delta) * EXTERIOR_SCALE_NUM + EXTERIOR_SCALE_ROUND) / EXTERIOR_SCALE_DEN) \
        : (((delta) * EXTERIOR_SCALE_NUM - EXTERIOR_SCALE_ROUND) / EXTERIOR_SCALE_DEN))
#define EXTERIOR_X(x) (PLAYER_START_X + EXTERIOR_SCALE_DELTA((x) - PLAYER_START_X))
#define EXTERIOR_Y(y) (PLAYER_START_Y + EXTERIOR_SCALE_DELTA((y) - PLAYER_START_Y))
#define EXTERIOR_SIZE(value) (((value) * EXTERIOR_SCALE_NUM + EXTERIOR_SCALE_ROUND) / EXTERIOR_SCALE_DEN)

#define STATION_FOOTPRINT_WIDTH 3
#define STATION_FOOTPRINT_HEIGHT 3
#define WORLD_INTERACTIVE_FOOTPRINT_SIZE 2
#define CRASH_CLUE_FOOTPRINT_SIZE 4
#define SHIP_FURNITURE_FOOTPRINT_SIZE 3
#define MONSTER_FOOTPRINT_SIZE 2
#define SHIP_PASSAGE_WIDTH 3
#define AIRLOCK_DOOR_HEIGHT 5

#define SHIP_CORRIDOR_X 47
#define SHIP_CORRIDOR_Y 51
#define SHIP_CORRIDOR_WIDTH 30
#define SHIP_CORRIDOR_HEIGHT SHIP_PASSAGE_WIDTH

#define SHIP_CARGO_HOLD_X 40
#define SHIP_CARGO_HOLD_Y 49
#define SHIP_CARGO_HOLD_WIDTH 7
#define SHIP_CARGO_HOLD_HEIGHT 7

#define SHIP_CREW_QUARTERS_X 44
#define SHIP_CREW_QUARTERS_Y 43
#define SHIP_CREW_QUARTERS_WIDTH 5
#define SHIP_CREW_QUARTERS_HEIGHT 5

#define SHIP_DIAGNOSTICS_X 44
#define SHIP_DIAGNOSTICS_Y 57
#define SHIP_DIAGNOSTICS_WIDTH 5
#define SHIP_DIAGNOSTICS_HEIGHT 5

#define SHIP_TERMINAL_BAY_X 56
#define SHIP_TERMINAL_BAY_Y 43
#define SHIP_TERMINAL_BAY_WIDTH 5
#define SHIP_TERMINAL_BAY_HEIGHT 5

#define PLAYER_RESPAWN_X (SHIP_TERMINAL_BAY_X + 2)
#define PLAYER_RESPAWN_Y (SHIP_TERMINAL_BAY_Y + SHIP_TERMINAL_BAY_HEIGHT - 1)
#define LOXI_ROOM_DOOR_X (SHIP_TERMINAL_BAY_X + 1)
#define LOXI_ROOM_DOOR_Y (SHIP_TERMINAL_BAY_Y + SHIP_TERMINAL_BAY_HEIGHT)
#define LOXI_ROOM_DOOR_WIDTH SHIP_PASSAGE_WIDTH

#define SHIP_LIFE_SUPPORT_X 56
#define SHIP_LIFE_SUPPORT_Y 57
#define SHIP_LIFE_SUPPORT_WIDTH 5
#define SHIP_LIFE_SUPPORT_HEIGHT 5

#define SHIP_WORKSHOP_X 68
#define SHIP_WORKSHOP_Y 43
#define SHIP_WORKSHOP_WIDTH 5
#define SHIP_WORKSHOP_HEIGHT 5

#define SHIP_POWER_BAY_X 68
#define SHIP_POWER_BAY_Y 57
#define SHIP_POWER_BAY_WIDTH 5
#define SHIP_POWER_BAY_HEIGHT 5

#define SHIP_AIRLOCK_LINK_X 77
#define SHIP_AIRLOCK_LINK_Y 50
#define SHIP_AIRLOCK_LINK_WIDTH 5
#define SHIP_AIRLOCK_LINK_HEIGHT 5

#define WORLD_MIN_X EXTERIOR_X(6)
#define WORLD_MIN_Y EXTERIOR_Y(6)
#define WORLD_MAX_X EXTERIOR_X(125)
#define WORLD_MAX_Y EXTERIOR_Y(103)

#define RUINS_MAIN_X EXTERIOR_X(40)
#define RUINS_MAIN_Y EXTERIOR_Y(6)
#define RUINS_MAIN_WIDTH EXTERIOR_SIZE(52)
#define RUINS_MAIN_HEIGHT EXTERIOR_SIZE(23)

#define RUINS_APPROACH_X EXTERIOR_X(48)
#define RUINS_APPROACH_Y EXTERIOR_Y(22)
#define RUINS_APPROACH_WIDTH EXTERIOR_SIZE(36)
#define RUINS_APPROACH_HEIGHT EXTERIOR_SIZE(18)

#define SWAMP_OUTER_X EXTERIOR_X(94)
#define SWAMP_OUTER_Y EXTERIOR_Y(34)
#define SWAMP_OUTER_WIDTH EXTERIOR_SIZE(26)
#define SWAMP_OUTER_HEIGHT EXTERIOR_SIZE(40)

#define SWAMP_FOREST_LINK_X EXTERIOR_X(94)
#define SWAMP_FOREST_LINK_Y EXTERIOR_Y(36)
#define SWAMP_FOREST_LINK_WIDTH EXTERIOR_SIZE(8)
#define SWAMP_FOREST_LINK_HEIGHT EXTERIOR_SIZE(12)

#define SWAMP_DEEP_X EXTERIOR_X(107)
#define SWAMP_DEEP_Y EXTERIOR_Y(21)
#define SWAMP_DEEP_WIDTH EXTERIOR_SIZE(19)
#define SWAMP_DEEP_HEIGHT EXTERIOR_SIZE(38)

#define LOXI_TERMINAL_X 57
#define LOXI_TERMINAL_Y 44
#define OXYGEN_CONSOLE_X 57
#define OXYGEN_CONSOLE_Y 58
#define WORKBENCH_X 69
#define WORKBENCH_Y 44
#define AIRLOCK_CONSOLE_X 74
#define AIRLOCK_CONSOLE_Y 48
#define COMM_RELAY_X EXTERIOR_X(100)
#define COMM_RELAY_Y EXTERIOR_Y(46)
#define CRASH_CLUE_X EXTERIOR_X(118)
#define CRASH_CLUE_Y EXTERIOR_Y(31)
#define ENERGY_CONSOLE_X 69
#define ENERGY_CONSOLE_Y 58
#define SIGNAL_TOWER_X EXTERIOR_X(64)
#define SIGNAL_TOWER_Y EXTERIOR_Y(8)

#define ENERGY_CORE_NODE_X EXTERIOR_X(120)
#define ENERGY_CORE_NODE_Y EXTERIOR_Y(50)

#define BOSS_ARENA_X EXTERIOR_X(9)
#define BOSS_ARENA_Y EXTERIOR_Y(9)
#define BOSS_ARENA_WIDTH EXTERIOR_SIZE(18)
#define BOSS_ARENA_HEIGHT EXTERIOR_SIZE(18)
#define BOSS_ARENA_ENTRY_TOP_Y (BOSS_ARENA_Y + BOSS_ARENA_HEIGHT - 5)
#define BOSS_ARENA_ENTRY_HEIGHT 3
#define BOSS_ARENA_PLAYER_ENTRY_X (BOSS_ARENA_X + BOSS_ARENA_WIDTH - 3)
#define BOSS_ARENA_PLAYER_ENTRY_Y (BOSS_ARENA_ENTRY_TOP_Y + 1)
#define BOSS_ARENA_BOSS_X (BOSS_ARENA_X + (BOSS_ARENA_WIDTH / 2) - 1)
#define BOSS_ARENA_BOSS_Y (BOSS_ARENA_Y + (BOSS_ARENA_HEIGHT / 2) - 1)
#define BOSS_ARENA_RETURN_X (SHIP_AIRLOCK_LINK_X + 1)
#define BOSS_ARENA_RETURN_Y (SHIP_AIRLOCK_LINK_Y + 2)

#define MONOLITH_A_X EXTERIOR_X(52)
#define MONOLITH_A_Y EXTERIOR_Y(16)
#define MONOLITH_B_X EXTERIOR_X(64)
#define MONOLITH_B_Y EXTERIOR_Y(12)
#define MONOLITH_C_X EXTERIOR_X(78)
#define MONOLITH_C_Y EXTERIOR_Y(17)

#define AIRLOCK_DOOR_X 82
#define AIRLOCK_DOOR_Y 52
#define AIRLOCK_DOOR_TOP_Y (AIRLOCK_DOOR_Y - (AIRLOCK_DOOR_HEIGHT / 2))
#define AIRLOCK_EXIT_WIDTH 5

#define SWAMP_GATE_X EXTERIOR_X(108)
#define SWAMP_GATE_WIDTH 2
#define SWAMP_GATE_TOP_Y EXTERIOR_Y(37)
#define SWAMP_GATE_HEIGHT EXTERIOR_SIZE(39)

#define RUINS_GATE_X EXTERIOR_X(68)
#define RUINS_GATE_WIDTH 2
#define RUINS_GATE_TOP_Y EXTERIOR_Y(23)
#define RUINS_GATE_HEIGHT EXTERIOR_SIZE(10)

#define ROPE_BARRIER_A_X EXTERIOR_X(103)
#define ROPE_BARRIER_A_Y EXTERIOR_Y(58)
#define ROPE_BARRIER_B_X EXTERIOR_X(103)
#define ROPE_BARRIER_B_Y EXTERIOR_Y(59)
#define ROPE_BARRIER_C_X EXTERIOR_X(103)
#define ROPE_BARRIER_C_Y EXTERIOR_Y(60)

#define BASE_CAMP_UNLOCK_STAGE 3
#define NPC_TALK_RANGE_TILES 2

#define MAX_RESOURCE_NODES 80
#define MAX_MONSTERS 24
#define MAX_LOGS 16

#define PLAYER_SPRITE_SHEET_ROWS 4
#define PLAYER_SPRITE_SHEET_COLS 6
#define PLAYER_SPRITE_ANIM_FPS 7.0f

#endif
