#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_TITLE "SpaceCraft Living"
#define WINDOW_WIDTH 1440
#define WINDOW_HEIGHT 900
#define WINDOW_MIN_WIDTH 1180
#define WINDOW_MIN_HEIGHT 760
#define WINDOW_MONITOR_FILL 0.86f
#define TARGET_FPS 60

#define TILE_SIZE 64
#define CAMERA_ZOOM 1.20f
#define MAP_WIDTH 100
#define MAP_HEIGHT 100

#define INITIAL_STAMINA 100.0f
#define BASE_MAX_STAMINA 100.0f
#define INITIAL_PRESSURE 0.0f
#define MAX_PRESSURE 100.0f
#define INITIAL_OXYGEN 100.0f
#define MAX_OXYGEN 100.0f
#define MAX_POISON 100.0f

#define NORMAL_MOVE_COOLDOWN 0.13f
#define LOW_STAMINA_MOVE_COOLDOWN 0.28f
#define CROUCH_MOVE_COOLDOWN 0.22f
#define BLOCKED_MOVE_COOLDOWN 0.09f
#define INPUT_BUFFER_TIME 0.12f
#define HOLD_REPEAT_INITIAL_DELAY 0.26f
#define HOLD_REPEAT_INTERVAL 0.10f
#define STAMINA_LOW_THRESHOLD 30.0f
#define STAMINA_MOVE_COST 1.0f
#define STAMINA_GATHER_COST 8.0f
#define STAMINA_SPECIAL_GATHER_COST 10.0f
#define STAMINA_ATTACK_COST 4.0f

#define SAFE_RECOVERY_INTERVAL 2.0f
#define SAFE_RECOVERY_AMOUNT 2.0f
#define PRESSURE_DAMAGE_INTERVAL 1.0f
#define HAZARD_TICK_INTERVAL 0.50f

#define DAY_DURATION_SECONDS 600.0f
#define DUSK_DURATION_SECONDS 120.0f
#define NIGHT_DURATION_SECONDS 480.0f
#define FULL_CYCLE_SECONDS (DAY_DURATION_SECONDS + DUSK_DURATION_SECONDS + NIGHT_DURATION_SECONDS)

#define PLAYER_START_X 35
#define PLAYER_START_Y 42

#define SHIP_CORE_X 37
#define SHIP_CORE_Y 42
#define WORKBENCH_X 44
#define WORKBENCH_Y 42
#define AIRLOCK_CONSOLE_X 58
#define AIRLOCK_CONSOLE_Y 42
#define COMM_RELAY_X 75
#define COMM_RELAY_Y 35
#define CRASH_CLUE_X 71
#define CRASH_CLUE_Y 54
#define ENERGY_CONSOLE_X 50
#define ENERGY_CONSOLE_Y 56
#define SIGNAL_TOWER_X 90
#define SIGNAL_TOWER_Y 62

#define MONOLITH_A_X 86
#define MONOLITH_A_Y 54
#define MONOLITH_B_X 92
#define MONOLITH_B_Y 49
#define MONOLITH_C_X 95
#define MONOLITH_C_Y 67

#define AIRLOCK_DOOR_X 63
#define AIRLOCK_DOOR_Y 42

#define BASE_CAMP_UNLOCK_STAGE 3
#define NPC_TALK_RANGE_TILES 2

#define MAX_RESOURCE_NODES 80
#define MAX_MONSTERS 24
#define MAX_LOGS 6

#endif
