#include "localization.h"

const char *Loc_GetUIFontSampleText(void) {
    return
        LOC_UI_STAMINA " "
        LOC_UI_PRESSURE " "
        LOC_UI_OXYGEN " "
        LOC_UI_STAGE " "
        LOC_UI_OBJECTIVE " "
        LOC_UI_DAY " "
        LOC_UI_EVENT " "
        LOC_UI_MENU_START " "
        LOC_UI_MENU_CONTINUE " "
        LOC_UI_MENU_EXIT " "
        LOC_UI_PAUSE_TITLE " "
        LOC_UI_PAUSE_CONTINUE " "
        LOC_UI_PAUSE_SAVE " "
        LOC_UI_PAUSE_MENU " "
        LOC_UI_COMM_TITLE " "
        LOC_UI_CRAFT_TITLE " "
        LOC_UI_HELP_TITLE " "
        LOC_UI_HELP_HINT " "
        LOC_UI_RECIPE_LOCKED " "
        LOC_UI_SAVE_SUCCESS " "
        LOC_UI_SAVE_FAILED " "
        LOC_UI_SAVE_MISSING " "
        LOC_UI_END_EXIT " "
        "SpaceCraft Living base forest swamp ruins heroic peaceful settlement failure "
        "resource crafting signal tower boss communicator repair oxygen stress stamina save attack stealth";
}
